packages:
  - 'apps/*'
  - 'identity'
  - 'caddy'
  - 'Holotap.co.uk'
allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
  unrs-resolver: set this to true or false
