/**
 * ============================================================
 *  HoloTapServer — Utility Layer
 *  Token Utilities (utils/token.ts)
 *
 *  Engineer: Raymond Newton (Founder‑Architect, E5357171)
 *  Version: 2.4.2
 *  Date: 15 August 2026
 * ============================================================
 *
 *  Purpose:
 *  ------------------------------------------------------------
 *  Provides deterministic QR-token decoding for Flow 6 identity.
 *  QR tokens generated by HoloTap Mobile/Web are base64-encoded
 *  JSON payloads containing identity metadata.
 *
 *  Guarantees:
 *  ------------------------------------------------------------
 *  - No destructive operations
 *  - No schema mutations
 *  - Pure decode logic only
 * ============================================================
 */

export async function decryptPayload(token: string): Promise<any> {
  try {
    // ------------------------------------------------------------
    // 1. Base64 decode
    // ------------------------------------------------------------
    const buffer = Buffer.from(token, "base64");

    // ------------------------------------------------------------
    // 2. Convert to UTF-8 JSON string
    // ------------------------------------------------------------
    const json = buffer.toString("utf8");

    // ------------------------------------------------------------
    // 3. Parse JSON payload
    // ------------------------------------------------------------
    return JSON.parse(json);
  } catch (err) {
    console.error("[QR] decryptPayload Error:", err);
    return null;
  }
}
